---

- name: Setup Testserver
  hosts: test
  become: true
  become_method: community.general.doas
  roles:
    - gentoo_base
  tags:
    - test

- name: Base Setup Production servers
  hosts: prod
  become: true
  become_method: community.general.doas
  roles:
    - gentoo_base
  tags:
    - prod
