---
- name: Add Networking to default runlevel
  ansible.builtin.service:
    name: net.{{ gentoochroot_networking.interface_name }}
    enabled: true

- name: Regenerate grub.cfg
  ansible.builtin.shell:
    cmd: "grub-mkconfig -o /boot/grub/grub.cfg"
    executable: /bin/bash
  register: result
  failed_when: result.rc != 0
  changed_when: result.rc == 0
