extra_packages:
  - qemu-guest-agent
  - zfs
  - nfs-utils

extra_services:
  - zfs-import:
    runlevel: boot
  - zfs-mount:
    runlevel: boot
  - zfs-share
  - nfs
  - qemu-guest-agent


portage_make:
  cpu_march: native
  go_amd: v3
  makeopts: -j6
  useflags:
  cpu_flags: aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 ssse3 vpclmulqdq
  video_card: virgl
  emerge_opts: --getbinpkg --keep-going
