- name: Set hostname
  ansible.builtin.copy:
    content: "{{ hostname }}\n"
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'

- name: Set timezone
  ansible.builtin.file:
    src: ../usr/share/zoneinfo/{{ timezone }}
    dest: /etc/localtime
    state: link

- name: Set keyboard layout
  ansible.builtin.lineinfile:
    path: /etc/conf.d/keymaps
    regexp: '^keymap='
    line: keymap="{{ keyboard_layout }}"

- name: Set locales
  ansible.builtin.blockinfile:
    path: /etc/locale.gen
    block: |
      {{ item }} UTF-8
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  loop: "{{ locale }}"

- name: Generate locales
  ansible.builtin.shell:
    cmd: locale-gen
    executable: /bin/bash
  register: result
  failed_when: result.rc != 0
  changed_when: false

- name: Set default locale to the first element of the locale list
  ansible.builtin.lineinfile:
    path: /etc/env.d/02locale
    regexp: '^LANG='
    line: LANG="{{ locale[0] }}"
