- name: Setup locales, hostname, timezone
  ansible.builtin.include_tasks:
    locales.yml

- name: Setup portage with correct make.conf
  ansible.builtin.include_tasks:
    portage.yml

- name: Do miscellaneous things
  ansible.builtin.include_tasks:
    misc.yml
