- name: Install git
  community.general.portage:
    package:
      - dev-vcs/git
    getbinpkg: true

- name: Copy repo.conf
  ansible.builtin.copy:
    src: repo.conf
    dest: /etc/portage/repos.conf/
    owner: root
    group: root
    mode: '0644'

- name: Run portage sync
  community.general.portage:
    sync: true
