extra_packages:
  - app-containers/docker
  - docker-compose

portage_make:
  cpu_march: native
  go_amd: v4
  makeopts: -j6
  useflags: |
    -a52 -aqua -systemd -emacs -xemacs -nntp -css -ldap -openquicktime -radius -bluetooth \
    -ios -ipod -motif -coreaudio -cdda -cdr -nas -smartcard -ibm -emboss -clamav bash-completion \
    vaapi lto pgo profile orc dist-kernel -postgres
  cpu_flags: test
  video_card: intel
  emerge_opts:
