- name: Configure the package manager
  ansible.builtin.include_tasks:
    portage.yml

- name: Configure the static IP-Address
  ansible.builtin.include_tasks:
    network.yml

- name: Finalize the installation
  ansible.builtin.include_tasks:
    finalize.yml

- name: Install bootloader
  ansible.builtin.include_tasks:
    grub.yml
