- name: Run emerge-webrsync
  ansible.builtin.shell:
    cmd: emerge-webrsync
    executable: /bin/bash
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0

- name: Create binhost to use
  ansible.builtin.template:
    src: gentoobinhost.j2
    dest: /etc/portage/binrepos.conf/gentoobinhost.conf
    mode: '0644'
    owner: root
    group: root

- name: Initialize keyring
  ansible.builtin.shell:
    cmd: getuto
    executable: /bin/bash
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0

- name: Copy useflag for gentoo-kernel-bin to package.use
  ansible.builtin.copy:
    content: "sys-kernel/installkernel dracut"
    dest: /etc/portage/package.use/kernel
    owner: root
    group: root
    mode: '0644'

- name: Install packages to boot the base installation
  community.general.portage:
    package:
      - gentoo-kernel-bin
      - grub
      - doas
    getbinpkg: true
